const Indonesia = [
  { provinsi: "Jawa Barat" },
  { provinsi: "Jawa Barat" },
  { provinsi: "Jawa Timur" },
  { provinsi: "Jawa Timur" },
  { provinsi: "Jawa Tengah" },
  { provinsi: "Jawa Barat" },
  { provinsi: "Sumatera Utara" },
  { provinsi: "Jawa Barat" },
  { provinsi: "Sumatera Utara" },
  { provinsi: "Yogyakarta" },
  { provinsi: "Yogyakarta" },
  { provinsi: "Sumatera Utara" },
  { provinsi: "Jakarta" },
  { provinsi: "Jakarta" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Sumatera Selatan" },
  { provinsi: "Jakarta" },
  { provinsi: "Jakarta" },
  { provinsi: "Jakarta" },
  { provinsi: "Jakarta" },
  { provinsi: "Palembang" },
];

export default Indonesia;
