const dataLaporan = [
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Perusakan Lingkungan" },
  { jenisLaporan: "Perusakan Lingkungan" },
  { jenisLaporan: "Perusakan Lingkungan" },
  { jenisLaporan: "Perusakan Lingkungan" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Pencemaran" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Eksploitasi Hewan" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Sampah" },
  { jenisLaporan: "Perusakan Lingkungan" },
];

export default dataLaporan;
